### ISSUE TITLE
AmazonCredential Constructor wrong parameters

### ISSUE THREAD

**Issue by zinsmeik** [abuzuhri/Amazon-SP-API-CSharp#21]
The new constructor does not set the refreshtoken of the class.
Constructor takes 5 Parameters while the methode sets 6 parameter 

```
        public AmazonCredential(string AccessKey, string SecretKey, string RoleArn, string ClientId, string ClientSecret)
        {
            this.AccessKey = AccessKey;
            this.SecretKey = SecretKey;
            this.RoleArn = RoleArn;
            this.ClientId = ClientId;
            this.ClientSecret = ClientSecret;
            this.RefreshToken = RefreshToken;
        }

```
and the CacheTokenData is only set when you create the class with the constructor without parameters

```
        public AmazonCredential()
        {
            CacheTokenData = new CacheTokenData();
        }

```

**Comment by abuzuhri** [comment]
Bug fixed in V1.0.16

**Comment by zinsmeik** [comment]
Thanks,
thats fast but RefreshToken is still not a parameter for the constructor ..or am I missing something?

**Comment by abuzuhri** [comment]
> Thanks,
> thats fast but RefreshToken is still not a parameter for the constructor ..or am I missing something?

Yes That true and fixed now on v1.0.17
